version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/frontend"         
    schedule:
      interval: "weekly" 
    commit-message:
      prefix: "frontend: "

  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "backend-python: "

  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "backend-node: "
