service: codeinspire

frameworkVersion: '3'

plugins:
  - serverless-python-requirements

custom:
  AuctionsTable:
    name: !Ref tipsTable
    arn: !GetAtt tipsTable.Arn

provider:
  name: aws
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'sa-east-1'}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:PutItem 
      Resource: 
        - ${self:custom.AuctionsTable.arn}
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.AuctionsTable.name}

resources:
  Resources:
    tipsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: tip_language
            AttributeType: S
          - AttributeName: tip_date
            AttributeType: S
        KeySchema:
          - AttributeName: tip_language
            KeyType: HASH
          - AttributeName: tip_date
            KeyType: RANGE 
        BillingMode: PAY_PER_REQUEST

functions:
  scheduleTipGenerator:
    handler: src.tip_generator.handler.run
    runtime: python3.10
    events:
      - schedule: cron(0 0 * * SUN *) 
    timeout: 30