service: codeinspire

package:
  individually: true

plugins:
  - serverless-python-requirements
  - serverless-bundle

custom:
  TipsTable:
    name: !Ref tipsTable
    arn: !GetAtt tipsTable.Arn

provider:
  name: aws
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'sa-east-1'}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan
      Resource: 
        - ${self:custom.TipsTable.arn}
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.TipsTable.name}

resources:
  Resources:
    tipsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: tip_language
            AttributeType: S
          - AttributeName: tip_date
            AttributeType: S
        KeySchema:
          - AttributeName: tip_language
            KeyType: HASH
          - AttributeName: tip_date
            KeyType: RANGE 
        BillingMode: PAY_PER_REQUEST

functions:
  scheduleTipGenerator:
    handler: src/tip_generator/handler.run
    runtime: python3.10
    events:     
      - schedule: cron(0 0 ? * SUN *) 
    timeout: 30

  getTips:
    handler: src/api/handlers/getTips.handler
    runtime: nodejs18.x
    events:
      - http:
          method: GET
          path: /tips

  